/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lenovo
 */
public class Desain extends javax.swing.JFrame {

    private String paketD = null;
    private String provider = null;

    public Desain() {
        initComponents();
    }

    void reset() {
        nama.setText("");
        paketData.clearSelection();
        paketD = null;
        provider = null;
        providerKartu.clearSelection();
        noHandphone.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paketData = new javax.swing.ButtonGroup();
        providerKartu = new javax.swing.ButtonGroup();
        close = new javax.swing.JPanel();
        minimize = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        noHandphone = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        dataTable = new javax.swing.JTable();
        clear = new javax.swing.JButton();
        remove = new javax.swing.JButton();
        update = new javax.swing.JButton();
        add = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 550));
        setUndecorated(true);
        getContentPane().setLayout(null);

        close.setOpaque(false);
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout closeLayout = new javax.swing.GroupLayout(close);
        close.setLayout(closeLayout);
        closeLayout.setHorizontalGroup(
            closeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        closeLayout.setVerticalGroup(
            closeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(close);
        close.setBounds(770, 0, 30, 30);

        minimize.setOpaque(false);
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout minimizeLayout = new javax.swing.GroupLayout(minimize);
        minimize.setLayout(minimizeLayout);
        minimizeLayout.setHorizontalGroup(
            minimizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        minimizeLayout.setVerticalGroup(
            minimizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(minimize);
        minimize.setBounds(740, 0, 30, 30);

        jLabel1.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 51));
        jLabel1.setText("Nama Pembeli");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 190, 130, 18);

        nama.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        getContentPane().add(nama);
        nama.setBounds(30, 210, 180, 24);

        jLabel2.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 51));
        jLabel2.setText("Paket Data");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 250, 100, 18);

        jLabel4.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 51));
        jLabel4.setText("Provider Kartu");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 360, 130, 18);

        jLabel5.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 51));
        jLabel5.setText("No Handphone");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 470, 130, 18);

        noHandphone.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        noHandphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noHandphoneActionPerformed(evt);
            }
        });
        getContentPane().add(noHandphone);
        noHandphone.setBounds(30, 490, 180, 24);

        dataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama", "Paket Data", "Provider kartu", "No Handphone"
            }
        ));
        dataTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dataTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(dataTable);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(240, 223, 540, 320);

        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear);
        clear.setBounds(650, 172, 130, 40);

        remove.setText("Remove");
        remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeActionPerformed(evt);
            }
        });
        getContentPane().add(remove);
        remove.setBounds(510, 172, 130, 40);

        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        getContentPane().add(update);
        update.setBounds(380, 172, 120, 40);

        add.setText("Add");
        add.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        add.setMaximumSize(new java.awt.Dimension(27, 18));
        add.setMinimumSize(new java.awt.Dimension(27, 18));
        add.setPreferredSize(new java.awt.Dimension(27, 18));
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        getContentPane().add(add);
        add.setBounds(238, 172, 130, 40);

        paketData.add(jRadioButton1);
        jRadioButton1.setLabel("2 GB");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(30, 270, 70, 25);

        paketData.add(jRadioButton2);
        jRadioButton2.setText("4 GB");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(120, 270, 70, 25);

        paketData.add(jRadioButton3);
        jRadioButton3.setText("12 GB");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton3);
        jRadioButton3.setBounds(30, 310, 70, 25);

        paketData.add(jRadioButton4);
        jRadioButton4.setText("24 GB");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton4);
        jRadioButton4.setBounds(120, 310, 70, 25);

        providerKartu.add(jRadioButton5);
        jRadioButton5.setText("XL");
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton5);
        jRadioButton5.setBounds(30, 420, 43, 25);

        providerKartu.add(jRadioButton6);
        jRadioButton6.setText("Telkomsel");
        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton6);
        jRadioButton6.setBounds(110, 380, 87, 25);

        providerKartu.add(jRadioButton7);
        jRadioButton7.setText("Indosat");
        jRadioButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton7);
        jRadioButton7.setBounds(30, 380, 71, 25);

        providerKartu.add(jRadioButton8);
        jRadioButton8.setText("Axis");
        jRadioButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton8);
        jRadioButton8.setBounds(150, 420, 51, 25);

        providerKartu.add(jRadioButton9);
        jRadioButton9.setText("TRI");
        jRadioButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton9);
        jRadioButton9.setBounds(90, 420, 49, 25);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/bg3 revisi lagi.png"))); // NOI18N
        getContentPane().add(Background);
        Background.setBounds(0, 0, 0, 0);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        DefaultTableModel model = (DefaultTableModel) dataTable.getModel();
        int deleteItem = JOptionPane.showConfirmDialog(null, "Apa kau yakin ingin Menghapus semua data pada tabel dan database?", "WARNING", JOptionPane.YES_NO_OPTION);
        if (deleteItem == JOptionPane.YES_OPTION) {
            model.setRowCount(0);
            reset();
        }
    }//GEN-LAST:event_clearActionPerformed

    private void removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeActionPerformed
        DefaultTableModel model = (DefaultTableModel) dataTable.getModel();
        if (dataTable.getRowCount() >= 1) {
            if (dataTable.getSelectedRow() != -1) {
                int deleteItem = JOptionPane.showConfirmDialog(null, "Apa kau yakin ingin Menghapus baris Data yang Kamu pilih?", "WARNING", JOptionPane.YES_NO_OPTION);
                if (deleteItem == JOptionPane.YES_OPTION) {
                    model.removeRow(dataTable.getSelectedRow());
                    reset();
                }
            } else {
                JOptionPane.showMessageDialog(null, "Belum memilih row yang ingin di delete");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Tidak ada Data pada Tabel");
        }
    }//GEN-LAST:event_removeActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        DefaultTableModel model = (DefaultTableModel) dataTable.getModel();
        if (dataTable.getRowCount() >= 1) {
            if (nama.getText().trim().equals("") || paketData.getSelection() == null || providerKartu.getSelection() == null || noHandphone.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(null, "Tolong isi dengan Lengkap");
            } else {
                model.setValueAt(nama.getText(), dataTable.getSelectedRow(), 0);
                model.setValueAt(paketD, dataTable.getSelectedRow(), 1);
                model.setValueAt(provider, dataTable.getSelectedRow(), 2);
                model.setValueAt(noHandphone.getText(), dataTable.getSelectedRow(), 3);
                reset();
                JOptionPane.showMessageDialog(null, "Update Berhasil");
            }
        } else {
            if (dataTable.getRowCount() == 0) {
                JOptionPane.showMessageDialog(null, "Belum memilih row yang ingin di update");
            } else {
                JOptionPane.showMessageDialog(null, "Tolong pilih lah 1 baris yang ingin diupdate");
            }
        }
    }//GEN-LAST:event_updateActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        DefaultTableModel model = (DefaultTableModel) dataTable.getModel();

        if (nama.getText().trim().equals("") || paketData.getSelection() == null || providerKartu.getSelection() == null || noHandphone.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Tolong isi dengan Lengkap");
        } else {
            model.addRow(new Object[]{nama.getText(), paketD, provider, noHandphone.getText()});
            reset();
        }
    }//GEN-LAST:event_addActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        paketD = "2 GB";
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        paketD = "4 GB";
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        paketD = "12 GB";
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        paketD = "24 GB";
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
        provider = "XL";
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton6ActionPerformed
        provider = "Telkomsel";
    }//GEN-LAST:event_jRadioButton6ActionPerformed

    private void jRadioButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton7ActionPerformed
        provider = "Indosat";
    }//GEN-LAST:event_jRadioButton7ActionPerformed

    private void jRadioButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton8ActionPerformed
        provider = "Axis";
    }//GEN-LAST:event_jRadioButton8ActionPerformed

    private void jRadioButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton9ActionPerformed
        provider = "TRI";
    }//GEN-LAST:event_jRadioButton9ActionPerformed

    private void noHandphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noHandphoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noHandphoneActionPerformed

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeMouseClicked

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        this.setState(1);
    }//GEN-LAST:event_minimizeMouseClicked

    private void dataTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataTableMouseClicked
        DefaultTableModel model = (DefaultTableModel) dataTable.getModel();
        String tNama = model.getValueAt(dataTable.getSelectedRow(), 0).toString();
        String tPaket = model.getValueAt(dataTable.getSelectedRow(), 1).toString();
        String tProvider = model.getValueAt(dataTable.getSelectedRow(), 2).toString();
        String tNo = model.getValueAt(dataTable.getSelectedRow(), 3).toString();

        nama.setText(tNama);
        switch (tPaket) {
            case "2 GB":
                jRadioButton1.setSelected(true);
                paketD = "2 GB";
                break;
            case "4 GB":
                jRadioButton2.setSelected(true);
                paketD = "4 GB";
                break;
            case "12 GB":
                jRadioButton3.setSelected(true);
                paketD = "12 GB";
                break;
            case "24 GB":
                jRadioButton4.setSelected(true);
                paketD = "24 GB";
                break;
            default:
        }
        switch (tProvider) {
            case "Indosat":
                jRadioButton7.setSelected(true);
                provider = "Indosat";
                break;
            case "Telkomsel":
                jRadioButton6.setSelected(true);
                provider = "Telkomsel";
                break;
            case "XL":
                jRadioButton5.setSelected(true);
                provider = "XL";
                break;
            case "TRI":
                jRadioButton9.setSelected(true);
                provider = "TRI";
                break;
            case "Axis":
                jRadioButton8.setSelected(true);
                provider = "Axis";
                break;
            default:
        }
        noHandphone.setText(tNo);
    }//GEN-LAST:event_dataTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Desain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Desain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Desain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Desain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Desain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton add;
    private javax.swing.JButton clear;
    private javax.swing.JPanel close;
    private javax.swing.JTable dataTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel minimize;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField noHandphone;
    private javax.swing.ButtonGroup paketData;
    private javax.swing.ButtonGroup providerKartu;
    private javax.swing.JButton remove;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
