/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class masuk extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public masuk() {
        initComponents();
    }

    public boolean cek(String id, String ke) {
        boolean nimExist = false;
        try {
            Connection conn = Koneksi.geConnection();
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM admin where " + ke + "='" + id + "'");

            while (rs.next()) {
                nimExist = true;
            }

        } catch (SQLException e) {
            System.out.println("Koneksi gagal " + e.toString());
        }
        return nimExist;
    }

    public boolean cekLogin(String idUser, String keUser, String idPass, String kePass) {
        
        try {
            Connection conn = Koneksi.geConnection();
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM admin where " + keUser + "='" + idUser + "' AND " + kePass + "='" + idPass + "'");

            if(rs.next()){
                if(idUser.equals(rs.getString(keUser)) && idPass.equals(rs.getString(kePass))){
                    return true;
                }else{
                    return false;
                }
            }else{
                return false;
            }

        } catch (SQLException e) {
            System.out.println("Koneksi gagal " + e.toString());
        }
        return false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        username = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        close = new javax.swing.JPanel();
        minimize = new javax.swing.JPanel();
        Logen = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        minimize1 = new javax.swing.JPanel();
        close1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 550));
        setUndecorated(true);
        getContentPane().setLayout(null);

        username.setBorder(null);
        username.setOpaque(false);
        username.setPreferredSize(new java.awt.Dimension(80, 24));
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        getContentPane().add(username);
        username.setBounds(320, 240, 200, 30);

        password.setBorder(null);
        password.setOpaque(false);
        getContentPane().add(password);
        password.setBounds(320, 290, 200, 30);

        close.setOpaque(false);
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });
        getContentPane().add(close);
        close.setBounds(770, 0, 30, 30);

        minimize.setOpaque(false);
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
        });
        getContentPane().add(minimize);
        minimize.setBounds(730, 0, 30, 30);

        Logen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogenMouseClicked(evt);
            }
        });
        getContentPane().add(Logen);
        Logen.setBounds(300, 340, 200, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/masuk.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 550);

        minimize1.setOpaque(false);
        minimize1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimize1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout minimize1Layout = new javax.swing.GroupLayout(minimize1);
        minimize1.setLayout(minimize1Layout);
        minimize1Layout.setHorizontalGroup(
            minimize1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        minimize1Layout.setVerticalGroup(
            minimize1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(minimize1);
        minimize1.setBounds(730, 0, 30, 30);

        close1.setOpaque(false);
        close1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                close1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout close1Layout = new javax.swing.GroupLayout(close1);
        close1.setLayout(close1Layout);
        close1Layout.setHorizontalGroup(
            close1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        close1Layout.setVerticalGroup(
            close1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(close1);
        close1.setBounds(770, 0, 30, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeMouseClicked

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        this.setState(1);
    }//GEN-LAST:event_minimizeMouseClicked

    private void LogenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogenMouseClicked
                if (username.getText().equals("") && password.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Username atau Password Kosong");
        } else {
            if ((cekLogin(username.getText(), "username", password.getText(), "password") == false)) {
                JOptionPane.showMessageDialog(this, "Username atau Password, Salah");
            } else {
                JOptionPane.showMessageDialog(this, "Login Berhasil");
                Database next = new Database();
                next.setVisible(true);
                next.pack();
                next.setLocationRelativeTo(null);
                next.setDefaultCloseOperation(Database.EXIT_ON_CLOSE);
                this.dispose();
            }
        }
    }//GEN-LAST:event_LogenMouseClicked

    private void minimize1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimize1MouseClicked
        this.setState(1);
    }//GEN-LAST:event_minimize1MouseClicked

    private void close1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_close1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(masuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(masuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(masuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(masuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new masuk().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Logen;
    private javax.swing.JPanel close;
    private javax.swing.JPanel close1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel minimize;
    private javax.swing.JPanel minimize1;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
