/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class Splash extends javax.swing.JFrame {

    /**
     * Creates new form loading
     */
    public Splash() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gif = new javax.swing.JLabel();
        kata = new javax.swing.JLabel();
        no = new javax.swing.JLabel();
        created = new javax.swing.JLabel();
        nama = new javax.swing.JLabel();
        npm = new javax.swing.JLabel();
        dari = new javax.swing.JLabel();
        loadingBar = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 550));
        setUndecorated(true);
        getContentPane().setLayout(null);
        getContentPane().add(gif);
        gif.setBounds(393, 130, 0, 30);

        kata.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        kata.setForeground(new java.awt.Color(255, 204, 0));
        kata.setText("Loading.");
        getContentPane().add(kata);
        kata.setBounds(10, 470, 110, 24);

        no.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        no.setForeground(new java.awt.Color(255, 0, 0));
        no.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        no.setText("0%");
        getContentPane().add(no);
        no.setBounds(0, 500, 800, 30);

        created.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        created.setForeground(new java.awt.Color(255, 0, 0));
        created.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        created.setText("Created By :");
        getContentPane().add(created);
        created.setBounds(0, 360, 800, 20);

        nama.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        nama.setForeground(new java.awt.Color(255, 102, 0));
        nama.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(nama);
        nama.setBounds(0, 390, 800, 20);

        npm.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        npm.setForeground(new java.awt.Color(255, 204, 0));
        npm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(npm);
        npm.setBounds(0, 420, 800, 20);

        dari.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        dari.setForeground(new java.awt.Color(204, 153, 0));
        dari.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(dari);
        dari.setBounds(0, 450, 800, 20);
        getContentPane().add(loadingBar);
        loadingBar.setBounds(0, 500, 800, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Splash.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 550);

        setBounds(0, 0, 800, 550);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>



    }
    
    public static void nextDB(){
        masuk next = new masuk();       
        next.setVisible(true);        
        next.pack();        
        next.setLocationRelativeTo(null);
        next.setDefaultCloseOperation(masuk.EXIT_ON_CLOSE);
        
    }
    public static void next(){
        Desain next = new Desain();       
        next.setVisible(true);        
        next.pack();        
        next.setLocationRelativeTo(null);
        next.setDefaultCloseOperation(Desain.EXIT_ON_CLOSE);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel created;
    public static javax.swing.JLabel dari;
    private javax.swing.JLabel gif;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel kata;
    public static javax.swing.JProgressBar loadingBar;
    public javax.swing.JLabel nama;
    public javax.swing.JLabel no;
    public static javax.swing.JLabel npm;
    // End of variables declaration//GEN-END:variables
}
